# Generated by Django 4.2.16 on 2024-11-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0034_alter_property_reference_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('expired', 'Expired'), ('valid', 'Valid'), ('canceled', 'Canceled')], default='valid', help_text='the status of the order', max_length=10)),
                ('order_reference_number', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique reference number for the order.', unique=True)),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], help_text='The type of order: Buy or Sell.', max_length=4)),
                ('order_price', models.DecimalField(decimal_places=2, help_text='The price per unit for the order.', max_digits=10)),
                ('order_quantity', models.DecimalField(decimal_places=2, help_text='The quantity of the asset in the order.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when the order was created.')),
                ('order_owner', models.ForeignKey(help_text='The user who owns this order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(help_text='the property linked to the orders', on_delete=django.db.models.deletion.CASCADE, related_name='property_orders_trading', to='property.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], help_text='Type of trade event: Buy or Sell.', max_length=4)),
                ('trade_price', models.DecimalField(decimal_places=2, help_text='The price at which the trade was executed.', max_digits=10)),
                ('trade_quantity', models.DecimalField(decimal_places=2, help_text='The quantity traded.', max_digits=10)),
                ('executed_at', models.DateTimeField(auto_now_add=True, help_text='The time when the trade was executed.')),
                ('related_order', models.ForeignKey(help_text='The order associated with this trade event (if any).', on_delete=django.db.models.deletion.CASCADE, to='orderbooks.order')),
                ('trading_owner', models.ForeignKey(help_text='The user who owns this trade event.', on_delete=django.db.models.deletion.CASCADE, related_name='trade_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
