# Generated by Django 4.2.16 on 2024-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.PositiveIntegerField(help_text='The price per unit for the order.'),
        ),
    ]
