# Generated by Django 4.2.16 on 2024-11-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbooks', '0003_order_order_blockchain_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_blockchain_identifier',
            field=models.CharField(blank=True, null=True),
        ),
    ]
