# Generated by Django 4.2.16 on 2024-12-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbooks', '0005_remove_trade_event_type_remove_trade_related_order_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='orderbooks__order_t_d5b0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='orderbooks__order_s_4ba1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_price'], name='orderbooks__order_p_e0193b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'order_price'], name='orderbooks__order_t_79320b_idx'),
        ),
    ]
