# Generated by Django 4.2.16 on 2024-10-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
