# Generated by Django 4.2.16 on 2024-10-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='rejection_reason',
        ),
    ]
