# Generated by Django 4.2.16 on 2024-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('transaction', 'Transaction'), ('rent_payout', 'Rent Payout'), ('new_property', 'New Property'), ('kyc_status', 'KYC Status')], db_index=True, max_length=50)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('involved_address', models.EmailField(db_index=True, max_length=254)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='notificatio_timesta_604ec2_idx'), models.Index(fields=['event_type', 'timestamp'], name='notificatio_event_t_5e1c35_idx'), models.Index(fields=['involved_address'], name='notificatio_involve_fbaafa_idx')],
            },
        ),
    ]
