# Generated by Django 4.2.16 on 2024-10-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('transaction', 'Transactions'), ('rent_payout', 'Rent Payout'), ('new_property', 'New Property'), ('kyc_status', 'KYC Status')], db_index=True, max_length=50),
        ),
    ]
