# Generated by Django 4.2.16 on 2025-02-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_activitylog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('user_action', 'User Action'), ('admin_broadcast', 'Admin Broadcast')], default='user_action', max_length=20, null=True),
        ),
    ]
