# Usa una imagen base de Python
FROM python:3.12.4-slim

# Establece un directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requisitos e instala dependencias
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código del proyecto al contenedor
COPY . /app/

# Expone el puerto en el que Django servirá la app
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]



# docker run -d -p 8000:8000 --name backend-container backend
