# Generated by Django 4.2.16 on 2024-09-25 18:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=100, unique=True)),
                ('wallet_address', models.CharField(max_length=42, unique=True, validators=[django.core.validators.RegexValidator(message="Invalid Ethereum wallet address. It must start with '0x' followed by 40 hexadecimal characters.", regex='^0x[a-fA-F0-9]{40}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('wallet_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
