# Generated by Django 4.2.16 on 2024-10-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_user',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
