# Generated by Django 4.2.16 on 2025-01-02 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Invalid Ethereum wallet address. It must start with '0x' followed by 40 hexadecimal characters.", regex='^0x[a-fA-F0-9]{40}$')]),
        ),
    ]
