# Generated by Django 4.2.16 on 2025-01-04 15:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0003_wallet_is_enabled_alter_wallet_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='allowed_address',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Invalid Ethereum wallet address. It must start with '0x' followed by 40 hexadecimal characters.", regex='^0x[a-fA-F0-9]{40}$')]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
