# Generated by Django 4.2.16 on 2025-01-04 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0004_wallet_allowed_address_alter_wallet_wallet_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
