# Generated by Django 4.2.16 on 2025-01-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_wallet_wallet_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_balance_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
