# Generated by Django 4.2.16 on 2025-01-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_wallet_last_balance_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='wallet_user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_address_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
