# Generated by Django 4.2.16 on 2025-02-04 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_wallet_updated_at_remove_wallet_wallet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, db_index=True, max_length=42, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Invalid Ethereum wallet address. It must start with '0x' followed by 40 hexadecimal characters.", regex='^0x[a-fA-F0-9]{40}$')]),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['wallet_address'], name='wallet_wall_wallet__d1426b_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['wallet_user_id'], name='wallet_wall_wallet__9f76bd_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['wallet_id'], name='wallet_wall_wallet__fcc2ac_idx'),
        ),
    ]
