# Generated by Django 4.2.16 on 2025-01-02 10:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0044_property_property_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_blockchain_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('token_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_tokens', models.PositiveIntegerField()),
                ('tokens_available', models.PositiveIntegerField()),
                ('token_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('token_type', models.CharField(choices=[('PropertyToken', 'Property Token'), ('Utility Token', 'Utility Token')], default='PropertyToken', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='property.property')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'indexes': [models.Index(fields=['token_blockchain_address'], name='blockchain__token_b_367699_idx'), models.Index(fields=['token_code'], name='blockchain__token_c_623279_idx')],
            },
        ),
    ]
