# Generated by Django 4.2.16 on 2025-01-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='total_tokens',
            new_name='initial_supply',
        ),
        migrations.AddField(
            model_name='token',
            name='locked_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
