# Generated by Django 4.2.16 on 2025-01-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_rename_initial_supply_token_total_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='locked_tokens',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='total_tokens',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
    ]
