# Generated by Django 4.2.16 on 2025-01-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_alter_token_locked_tokens_alter_token_total_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='max_allowed_investment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
