# Generated by Django 4.2.16 on 2025-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_token_max_allowed_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tokens_available',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
    ]
