# Generated by Django 4.2.15 on 2024-09-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_tokenstransaction_property_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstransaction',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='property.property'),
        ),
    ]
