# Generated by Django 4.2.15 on 2024-09-02 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_tokenstransaction_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tokenstransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
