# Generated by Django 4.2.16 on 2024-09-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_rol'),
        ('property', '0008_property_projected_annual_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_profile',
            field=models.ForeignKey(blank=True, help_text='The PropertyOwnerProfile associated with this property.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='users.propertyownerprofile'),
        ),
    ]
