# Generated by Django 4.2.16 on 2024-09-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_owner_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='blockchain_address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='token_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tokensSold',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_tokens',
        ),
    ]
