# Generated by Django 4.2.16 on 2024-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_remove_property_blockchain_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(help_text='Number of bathrooms in the property, supporting whole numbers only.'),
        ),
    ]
