# Generated by Django 4.2.16 on 2024-09-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_property_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(blank=True, help_text="A boolean to control if the property is listed or if it's a coming soon property.", null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('listing', 'Listing'), ('published', 'Published'), ('draft', 'Draft'), ('coming_soon', 'Coming Soon'), ('rejected', 'Rejected')], default='listing', help_text='The current status of the property listing.', max_length=20),
        ),
    ]
