# Generated by Django 4.2.16 on 2024-09-12 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0012_alter_property_active_alter_property_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tokens', models.PositiveIntegerField()),
                ('owner_user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_code', models.CharField(max_length=255, unique=True)),
                ('total_tokens', models.PositiveIntegerField()),
                ('tokens_available', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('additional_details', models.JSONField(blank=True, null=True)),
                ('event', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('CANCELLATION', 'Cancellation')], max_length=20)),
            ],
            options={
                'verbose_name': 'Token Transaction',
                'verbose_name_plural': 'Token Transactions',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='TokensTransaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='property_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='property.property'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='property.token'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_owner_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='token',
            name='property_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='property.property'),
        ),
        migrations.AddField(
            model_name='propertytoken',
            name='property_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tokens', to='property.property'),
        ),
        migrations.AddField(
            model_name='propertytoken',
            name='token_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tokens', to='property.token'),
        ),
    ]
