# Generated by Django 4.2.16 on 2024-09-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytoken',
            name='token_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
