# Generated by Django 4.2.16 on 2024-09-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_propertytoken_token_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytoken',
            name='token_price',
        ),
        migrations.AddField(
            model_name='token',
            name='token_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
