# Generated by Django 4.2.16 on 2024-09-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_propertytoken_token_price_token_token_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='property_code',
            new_name='property_id',
        ),
    ]
