# Generated by Django 4.2.16 on 2024-09-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_rename_property_code_transaction_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_tokens_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
