# Generated by Django 4.2.16 on 2024-09-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_transaction_transaction_tokens_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='equity_listed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='referene_number',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
