# Generated by Django 4.2.16 on 2024-10-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_property_equity_listed_transaction_referene_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ownershipPercentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
