# Generated by Django 4.2.16 on 2024-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_property_ownershippercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tenant_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='vacancy_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
