# Generated by Django 4.2.16 on 2024-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_property_tenant_turnover_property_vacancy_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tenant_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='vacancy_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
