# Generated by Django 4.2.16 on 2024-10-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_alter_property_tenant_turnover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tenant_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vacancy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('net_asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='property.property')),
            ],
        ),
    ]
