# Generated by Django 4.2.16 on 2024-10-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
