# Generated by Django 4.2.16 on 2024-10-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_property_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='investment_category',
            field=models.CharField(blank=True, null=True),
        ),
    ]
