# Generated by Django 4.2.16 on 2024-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_property_investment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
