# Generated by Django 4.2.16 on 2024-11-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_region_submitapplication_country_and_more'),
        ('property', '0029_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='application_ref_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_application', to='users.submitapplication'),
        ),
    ]
