# Generated by Django 4.2.16 on 2024-11-22 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_property_property_blockchain_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reference_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
