# Generated by Django 4.2.16 on 2024-11-22 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0033_property_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='reference_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
