# Generated by Django 4.2.16 on 2024-11-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0035_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_scrow_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
