# Generated by Django 4.2.16 on 2024-12-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0037_remove_property_application_ref_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='referene_number',
        ),
    ]
