# Generated by Django 4.2.16 on 2024-12-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0038_remove_transaction_referene_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='reference_number',
        ),
    ]
