# Generated by Django 4.2.16 on 2025-01-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0039_remove_property_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='investment_category',
            field=models.CharField(choices=[('core', 'Core'), ('opportunistic', 'Opportunistic')], default='core', max_length=25),
        ),
    ]
