# Generated by Django 4.2.16 on 2025-01-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_alter_property_investment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reference_number',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
