# Generated by Django 4.2.16 on 2025-01-01 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0042_property_reference_number_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='reference_number',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Automatically generated unique identifier for the property.', unique=True),
        ),
    ]
