# Generated by Django 4.2.16 on 2025-01-01 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0043_alter_property_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_owner',
            field=models.ForeignKey(blank=True, help_text='El usuario que posee o gestiona esta propiedad.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
