# Generated by Django 4.2.16 on 2025-01-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('property', '0044_property_property_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='token_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_owner_code',
        ),
        migrations.AlterField(
            model_name='propertytoken',
            name='token_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tokens', to='blockchain.token'),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
