# Generated by Django 4.2.16 on 2025-01-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0045_remove_transaction_property_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='active',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_code',
        ),
    ]
