# Generated by Django 4.2.16 on 2025-01-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0046_remove_property_active_remove_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='propertytoken',
            index=models.Index(fields=['property_code', 'owner_user_code'], name='property_pr_propert_b3a811_idx'),
        ),
    ]
