# Generated by Django 4.2.16 on 2025-01-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0047_propertytoken_property_pr_propert_b3a811_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ipfs_nformation_url',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
