# Generated by Django 4.2.16 on 2025-01-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0048_property_ipfs_nformation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='batchId',
            field=models.CharField(blank=True, null=True),
        ),
    ]
