# Generated by Django 4.2.16 on 2025-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0049_property_batchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='batchId',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
