# Generated by Django 4.2.16 on 2025-02-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0050_alter_property_batchid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='admin_fields_completed',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_fields_completed',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_scrow_address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rejection_reason_comment',
        ),
    ]
