# Generated by Django 4.2.16 on 2025-02-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0051_remove_property_admin_fields_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rental_income_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
