# Generated by Django 4.2.16 on 2025-02-03 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0052_property_rental_income_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rental_income_date',
        ),
        migrations.AddField(
            model_name='property',
            name='rental_due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
