# Generated by Django 4.2.16 on 2025-02-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0054_property_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cap_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The capitalization rate of the property as a percentage.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_increase_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The expected percentage increase in property value over time.', max_digits=5, null=True),
        ),
    ]
