# Generated by Django 4.2.16 on 2025-02-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0055_property_cap_rate_property_price_increase_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyupdates',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='propertyupdates',
            name='updated_at',
        ),
    ]
