# Generated by Django 4.2.16 on 2025-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0056_remove_propertyupdates_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyupdates',
            name='update_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
