# Generated by Django 4.2.16 on 2025-02-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0058_property_property_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='proeprty_token_structure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
