# Generated by Django 4.2.16 on 2025-02-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_owner_code'], name='transaction_transac_ce1ccb_idx'),
        ),
    ]
