# Generated by Django 4.2.16 on 2024-09-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_propertyowner_remove_propertyadminprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Owner', 'Property Owner'), ('Investor', 'Investor')], default='owner', max_length=20),
        ),
    ]
