# Generated by Django 4.2.16 on 2024-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
