# Generated by Django 4.2.16 on 2024-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='national_insurance',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
