# Generated by Django 4.2.16 on 2024-11-13 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_alter_property_options_and_more'),
        ('users', '0005_customuser_contact_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnBehalfInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on_behalf_of_organization', models.BooleanField(default=False)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position_or_role', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_type', models.CharField(blank=True, choices=[('LLC', 'LLC'), ('corporation', 'Corporation'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=100, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_tax_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_broker_dealer', models.BooleanField(default=False)),
                ('relationship_with_asset', models.TextField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='on_behalf_profile', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
