# Generated by Django 4.2.16 on 2024-11-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_onbehalfinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnBehalfInformation',
        ),
    ]
