# Generated by Django 4.2.16 on 2024-11-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_onbehalfinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_address', models.CharField(max_length=255)),
                ('national_insurance', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('is_property_submitted_for_self', models.BooleanField(default=True)),
                ('is_on_behalf_of_organization', models.BooleanField(default=False)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position_or_role', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_tax_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_broker_dealer', models.BooleanField(default=False)),
                ('relationship_with_asset', models.TextField(blank=True, null=True)),
                ('preferred_communication_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10)),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('office', 'Office'), ('retail', 'Retail'), ('industrial', 'Industrial'), ('mixed_use', 'Mixed-Use'), ('residential', 'Residential')], max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('total_square_footage', models.FloatField()),
                ('year_built', models.IntegerField()),
                ('amenities', models.TextField()),
                ('current_use_of_property', models.CharField(choices=[('rented', 'Rented'), ('owner_occupied', 'Owner-Occupied'), ('vacant', 'Vacant')], max_length=100)),
                ('property_images', models.FileField(blank=True, null=True, upload_to='property_images/')),
                ('floor_plans', models.FileField(blank=True, null=True, upload_to='floor_plans/')),
                ('video_tour', models.FileField(blank=True, null=True, upload_to='video_tours/')),
                ('market_value', models.FloatField()),
                ('equity_percentage_to_tokenize', models.FloatField()),
                ('lease_terms', models.TextField()),
                ('current_occupancy_rate', models.FloatField()),
                ('revenue_last_tax_year', models.FloatField()),
                ('loan_details', models.TextField(blank=True, null=True)),
                ('operating_expenses', models.TextField()),
                ('property_deed', models.FileField(blank=True, null=True, upload_to='legal_documents/')),
                ('lease_agreements', models.FileField(blank=True, null=True, upload_to='legal_documents/')),
                ('tax_compliance_documents', models.FileField(blank=True, null=True, upload_to='legal_documents/')),
                ('additional_comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
