# Generated by Django 4.2.16 on 2024-11-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_region_submitapplication_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitapplication',
            name='application_status',
            field=models.CharField(choices=[('acepted', 'Acepted'), ('draf', 'Draft'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='draf', max_length=20),
        ),
    ]
