# Generated by Django 4.2.16 on 2024-12-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_investorprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
    ]
